export const ENCRYPTER_PROVIDER = 'ENCRYPTER_PROVIDER';
export const TOKEN_PROVIDER = 'TOKEN_PROVIDER';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const SOCIAL_MEDIA_REPOSITORY = 'SOCIAL_MEDIA_REPOSITORY';
export const PAGE_CUSTOMIZE_REPOSITORY = 'PAGE_CUSTOMIZE_REPOSITORY';
export const DONATION_REPOSITORY = 'DONATION_REPOSITORY';
export const STORAGE = 'STORAGE';
