name: "Continuous intregation pipeline"

on:
  push:
    branches:
      - master

jobs:
  donation-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: "Install packages"
        run: cd backend && npm install

      - name: "Run unit tests"
        run: cd backend && npm test ./src/donation/

  user-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: "Install packages"
        run: cd backend && npm install
        
      - name: "Run unit tests"
        run: cd backend && npm test ./src/users/

  page-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: "Install packages"
        run: cd backend && npm install
        
      - name: "Run unit tests"
        run: cd backend && npm test ./src/page-customized/
