name: "Continuous intregation pipeline"

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: "Install packages"
        run: cd backend && npm install

      - name: "Run unit tests"
        run: cd backend && npm test ./src/
      
      - name: "Setting up to run integration tests"
        run: |
          echo "" > .env.testing && \
          echo ${{ secrets.DB_URL }} >> .env.testing && \
          echo ${{ secrets.JWT_SECRET }} >> .env.testing && \
          echo ${{ secrets.AWS_ACCESS_ID }} >> .env.testing && \
          echo ${{ secrets.AWS_SECRET_ACCESS }} >> .env.testing && \
          echo ${{ secrets.BUCKET }} >> .env.testing && \

      - name: "Run integration tests"
        run: |
          cd backend && npm run test:e2e ./test/user.e2e-spec.ts && \
          npm run test:e2e ./test/page-customazed.e2e-spec.ts && \
          npm run test:e2e ./test/donnation.e2e-spec.ts

