name: "Continuous intregation pipeline"

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: "Install packages"
        run: cd backend && npm install

      - name: "Run unit tests"
        run: cd backend && npm test

      - name: Start containers
        run: cd backend && docker-compose -f docker-compose.testing.yml up -d

      - name: "Setting up to run integration tests"
        shell: bash
        run: |
          echo "" > .env.testing 
          echo "DB_URL='${{ secrets.DB_URL }}'" >> .env.testing
          echo "JWT_SECRET='${{ secrets.JWT_SECRET }}'" >> .env.testing 
          echo "AWS_ACCESS_ID='${{ secrets.AWS_ACCESS_ID }}'" >> .env.testing 
          echo "AWS_SECRET_ACCESS='${{ secrets.AWS_SECRET_ACCESS }}'" >> .env.testing 
          echo "BUCKET='${{ secrets.BUCKET }}'" >> .env.testing

      - name: Run migrations test database
        run: cd backend && NODE_ENV=testing npm run typeorm:run-migrations

      - name: "Run integration tests"
        run: cd backend && npm run test:e2e 
