name: "Continuous intregation pipeline"

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: "Install packages"
        run: cd backend && npm install

      - name: "Run unit tests"
        run: cd backend && npm test ./src/
      
      - name: "Setting up to run integration tests"
        shell: bash
        run: |
          echo "" > .env.testing 
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env.testing
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.testing 
          echo "AWS_ACCESS_ID=${{ secrets.AWS_ACCESS_ID }}" >> .env.testing 
          echo "AWS_SECRET_ACCESS=${{ secrets.AWS_SECRET_ACCESS }}" >> .env.testing 
          echo "BUCKET=${{ secrets.BUCKET }}" >> .env.testing

      - name: "Run integration tests"
        shell: bash
        run: |
          cd backend 
          cd backend && npm run test:e2e ./test/user.e2e-spec.ts && \
          cd backend && npm run test:e2e ./test/page-customazed.e2e-spec.ts && \
          cd backend && npm run test:e2e ./test/donnation.e2e-spec.ts 

